In [ ]:
import numpy as np

Part 1: Creating and Reshaping Arrays

In [ ]:
arr1 = np.linspace(0,50,10)
arr2 = np.random.randint(5,20,9)
arr2 = arr2.reshape(3,3)
print(arr1)
print(arr2)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
[[10  5 10]
 [ 7 17  6]
 [17 19 19]]


In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)

1
2
(10,)
(3, 3)


In [ ]:
arr1 = arr1.reshape(2,5)
print(arr1)
arr1= arr1.reshape(-1)
print(arr1)

[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


Part 2: Indexing and Slicing

In [ ]:
#Indexing
print(arr2)
print(arr2[1][2])
print(arr2[0])
print(arr2[1])

#Slicing
print(arr2[0:2, 1:])
print(arr1[0:4])
print(arr1[::-1])

[[10  5 10]
 [ 7 17  6]
 [17 19 19]]
6
[10  5 10]
[ 7 17  6]
[[ 5 10]
 [17  6]]
[ 0.          5.55555556 11.11111111 16.66666667]
[50.         44.44444444 38.88888889 33.33333333 27.77777778 22.22222222
 16.66666667 11.11111111  5.55555556  0.        ]


Part 3: Array Operations

In [ ]:
arr3 = np.arange(1,11)
print(np.add(arr1,arr3))
print(np.multiply(arr1,arr3))
print(np.subtract(arr3,5))
print(arr1+arr3)
print(arr1*arr3)

[ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
[  0.          11.11111111  33.33333333  66.66666667 111.11111111
 166.66666667 233.33333333 311.11111111 400.         500.        ]
[-4 -3 -2 -1  0  1  2  3  4  5]
[ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
[  0.          11.11111111  33.33333333  66.66666667 111.11111111
 166.66666667 233.33333333 311.11111111 400.         500.        ]


In [ ]:
arr4 = np.random.rand(5)
print(arr4)
arr5 = np.random.randint(-1,1,5)
print(arr5)

[0.50017474 0.97414642 0.27979423 0.07475865 0.91856327]
[ 0 -1 -1 -1  0]


Part 4: Random Number Generation and Copying

In [ ]:
n = int(input("Enter n:"))
arr6 = np.random.randint(1,100, size=(n,n))
print(arr6)
print(sum(arr6))

Enter n:3
[[21 94 94]
 [99 30 80]
 [15  3 41]]
[135 127 215]
